---
title: "Analisi Esplorativa"
output: html_notebook
---

Caricamento delle Librerie necessarie
```{r setup, include=FALSE}
# Caricamento Librerie
library(ggplot2)
library(dplyr)
library(here)
```

Caricamento del Dataset
```{r}
# Carica il dataset
file.exists("C://Users//franc//Documents//ProgettoSAD//dataset//data.csv")
dataset <- read.csv(here("dataset/data.csv"), sep = ";", header = TRUE)

# Visualizza le prime e le ultime righe del dataset per verificare che sia stato caricato correttamente
head(dataset)
tail(dataset)
```
Dimensione del Dataset
```{r}
print(paste("Righe: ", nrow(dataset)))
print(paste("Colonne: ", ncol(dataset)))
```



Distribuzione Variabile Target
```{r}
# Raggruppa i dati per la colonna Target e conta le occorrenze di ogni categoria
dati_target <- dataset %>%
  group_by(Target) %>%
  summarise(count = n()) %>%
  mutate(percentage = round((count / sum(count)) * 100, 1))  # Calcola la percentuale

# Crea il grafico a torta con le percentuali
ggplot(dati_target, aes(x = "", y = count, fill = Target)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y") +
  labs(title = "Distribuzione dei valori 'Target'") +
  theme_void() +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust = 0.5))

```

Analisi Feature Marital Status
```{r}
# Crea un vettore di etichette per lo stato civile
dataset$`Marital.status` <- factor(dataset$`Marital.status`, 
                                    levels = c(1, 2, 3, 4, 5, 6),
                                    labels = c("Single", "Married", "Widower", "Divorced", "Facto Union", "Separated"))
# Controllo Valori NULL
dataset[is.na(dataset$`Marital.status`), ]

# Calcola la frequenza massima per aumentare il limite superiore
freq <- table(dataset$`Marital.status`)
max_freq <- max(freq)

# Crea di nuovo il grafico a barre con le nuove etichette
bp <- barplot(table(dataset$`Marital.status`), main = "Distribuzione dello Stato Civile", 
        xlab = "Stato Civile", 
        ylab = "Frequenza",
        ylim = c(0, max_freq * 1.2),
        col = rainbow(6))

# Aggiungi le frequenze sopra ogni barra
text(x = bp, y = freq, labels = freq, pos = 3, cex = 0.8, col = "black")
```

Application Mode
```{r}
# Crea un vettore di etichette per la modalità di immatricolazione
#dataset$`Application.mode` <- factor(dataset$`Application.mode`, 
    #                                 levels = c(1, 2, 5, 7, 10, 15, 16, 17, 18, 26, 27, 39, 42, 43, 44, 51, 53, 57),
  #                                   labels = c("1st phase - general contingent",
   #                                             "Ordinance No. 612/93",
    #                                            "1st phase - special contingent (Azores Island)",
     #                                           "Holders of other higher courses",
      #                                          "Ordinance No. 854-B/99",
       #                                         "International student (bachelor)",
        #                                        "1st phase - special contingent (Madeira Island)",
         #                                       "2nd phase - general contingent",
          #                                      "3rd phase - general contingent",
           #                                     "Ordinance No. 533-A/99, item b2) (Different Plan)",
            #                                    "Ordinance No. 533-A/99, item b3 (Other Institution)",
             #                                   "Over 23 years old",
              #                                  "Transfer",
               #                                 "Change of course",
                #                                "Technological specialization diploma holders",
                 #                               "Change of institution/course",
                  #                              "Short cycle diploma holders",
                   #                             "Change of institution/course (International)"))

# Controllo Valori NULL
dataset[is.na(dataset$`Application.mode`), ]

# Calcola la frequenza massima per aumentare il limite superiore
freq <- table(dataset$`Application.mode`)
max_freq <- max(freq)

# Crea il BarPlot con le nuove etichette
bp <- barplot(freq, main = "Distribuzione della Modalità di Immatricolazione", 
              xlab = "Modalità di Immatricolazione", 
              ylab = "Frequenza",
              ylim = c(0, max_freq * 1.2),
              col = rainbow(length(freq)),
              space = 1)

# Aggiungi le frequenze sopra ogni barra
text(x = bp, y = freq, labels = freq, pos = 3, cex = 0.8, col = "black")


```
Application Order
```{r}
# Controllo Valori NULL
dataset[is.na(dataset$`Application.order`), ]

# Calcola la frequenza massima per aumentare il limite superiore
freq <- table(dataset$`Application.order`)
max_freq <- max(freq)

# Crea il BarPlot con le nuove etichette
bp <- barplot(freq, main = "Distribuzione dell`ordine di immatricolazione", 
              xlab = "Ordine di Immatricolazione", 
              ylab = "Frequenza",
              ylim = c(0, max_freq * 1.2),
              col = rainbow(length(freq)),
              space = 1)

# Aggiungi le frequenze sopra ogni barra
text(x = bp, y = freq, labels = freq, pos = 3, cex = 0.8, col = "black")

# Estrai le righe in cui Application Order è uguale a 0 o 9
righe_anomale <- dataset[dataset$`Application.order` %in% c(0, 9), ]

# Visualizza le righe estratte
print(righe_anomale)
```
Course
```{r}
# Controllo Valori NULL
dataset[is.na(dataset$`Course`), ]

# Distribuzione di Frequenza dei Corsi di Laurea
freq <- table(dataset$`Course`)
max_freq <- max(freq)
bp <- barplot(freq, main = "Distribuzione deli Corsi di Laurea", 
              xlab = "Corso di Laurea", 
              ylab = "Frequenza",
              ylim = c(0, max_freq * 1.2),
              col = rainbow(length(freq)),
              space = 1,
              las = 2)

text(x = bp, y = freq, labels = freq, pos = 3, cex = 0.8, col = "black")

# Corsi di Laurea in base all`abbandono
# Imposta un margine superiore più grande
par(mar = c(5, 4, 6, 2))  # Aumenta il margine superiore (terzo valore) per fare spazio al titolo

# Crea il grafico a barre affiancate senza titolo
bp <- barplot(t(target_percentages), 
              beside = TRUE,
              xlab = "Corso di Laurea", 
              ylab = "Percentuale",
              col = c("red", "blue", "green"), 
              las = 2,
              space = c(0, 2))

# Aggiungi il titolo con una distanza extra dal grafico
title(main = "Percentuali di Target per Corso di Laurea", line = 3)

# Aggiungi la legenda sotto il titolo
legend("top", inset = c(0, -0.2), 
       legend = c("Dropout", "Enrolled", "Graduate"), 
       fill = c("red", "blue", "green"), 
       xpd = TRUE, horiz = TRUE)


```

