---
title: "Notebook di Prova"
output: html_notebook
---

Caricamento delle Librerie necessarie
```{r setup, include=FALSE}
# Caricamento Librerie
library(ggplot2)
library(dplyr)

```

Caricamento del Dataset
```{r}
# Carica il dataset
dataset <- read.csv("dataset/data.csv", sep = ";", header = TRUE)

# Visualizza le prime righe del dataset per verificare che sia stato caricato correttamente
print(dataset)
```

Creazione Grafico a Torta
```{r}
# Raggruppa i dati per la colonna GDP.Target e conta le occorrenze di ogni categoria
dati_target <- dataset %>%
  group_by(Target) %>%
  summarise(count = n()) %>%
  mutate(percentage = round((count / sum(count)) * 100, 1))  # Calcola la percentuale

# Crea il grafico a torta con le percentuali
ggplot(dati_target, aes(x = "", y = count, fill = Target)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y") +
  labs(title = "Distribuzione dei valori in 'Target'") +
  theme_void() +
  geom_text(aes(label = paste0(percentage, "%")), position = position_stack(vjust = 0.5))

```

