Nuova distribuzione:

Single: 88.6%
Married or Partner: 9.2% (Married e Facto Union)
Previously Married: 2.3% (Divorced, Widower, Legally Separated)
```{r}
##### MARITAL STATUS #####
# Caricamento Dataset
library(here)
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Librerie necessarie
library(ggplot2)
library(dplyr)
library(gridExtra)

# Mappatura delle categorie originali
data$Marital_status <- factor(data$Marital_status, 
                              levels = c(1, 2, 3, 4, 5, 6), 
                              labels = c("1-Single", "2-Married", "3-Widower", 
                                         "4-Divorced", "5-Facto Union", "6-Legally Separated"))

# Creazione della variabile accorpata con nuovi livelli numerati
data$Marital_status_grouped <- recode(data$Marital_status,
                                      "1-Single" = "1-Single",
                                      "2-Married" = "2-Married",
                                      "5-Facto Union" = "2-Married",
                                      "3-Widower" = "3-Previously Married",
                                      "4-Divorced" = "3-Previously Married",
                                      "6-Legally Separated" = "3-Previously Married")

# Convertire in fattore
data$Marital_status_grouped <- factor(data$Marital_status_grouped, 
                                      levels = c("1-Single", "2-Married", "3-Previously Married"))

# Calcolo delle frequenze relative per il dataset originale
freq_original <- table(data$Marital_status)
original_data <- data.frame(Status = names(freq_original), 
                            Count = as.numeric(freq_original))
original_data$Perc <- original_data$Count / sum(original_data$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate
freq_grouped <- table(data$Marital_status_grouped)
grouped_data <- data.frame(Status = names(freq_grouped), 
                           Count = as.numeric(freq_grouped))
grouped_data$Perc <- grouped_data$Count / sum(grouped_data$Count) * 100

# Creazione del barplot originale
p1 <- ggplot(original_data, aes(x = Status, y = Perc, fill = Status)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Marital Status (Originale)", x = "Marital Status", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") 

# Creazione del barplot con le categorie accorpate
p2 <- ggplot(grouped_data, aes(x = Status, y = Perc, fill = Status)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Marital Status (Accorpato)", x = "Marital Status", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") 

# Affiancare i due grafici
grid.arrange(p1, p2, ncol = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Marital_Status_Comparison.pdf", plot = grid.arrange(p1, p2, ncol = 2), width = 16, height = 6)

```

```{r}
####### NATIONALITY #######

# Librerie
library(ggplot2)
library(dplyr)
library(here)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Creazione della variabile accorpata con due categorie: Portuguese vs Other Nationality
data$Nationality_grouped <- recode(data$Nationality,
                                   "1" = "1-Portuguese", 
                                   .default = "2-Other Nationality") # Tutte le altre nazionalità vengono accorpate

# Convertire in fattore con ordine predefinito
data$Nationality_grouped <- factor(data$Nationality_grouped, 
                                   levels = c("1-Portuguese", "2-Other Nationality"))

# Calcolo delle frequenze relative per il dataset originale
freq_original <- table(data$Nationality)
original_data <- data.frame(Nationality = names(freq_original), 
                            Count = as.numeric(freq_original))
original_data$Perc <- original_data$Count / sum(original_data$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate
freq_grouped <- table(data$Nationality_grouped)
grouped_data <- data.frame(Nationality = names(freq_grouped), 
                           Count = as.numeric(freq_grouped))
grouped_data$Perc <- grouped_data$Count / sum(grouped_data$Count) * 100

# Creazione del barplot originale
p1 <- ggplot(original_data, aes(x = Nationality, y = Perc, fill = Nationality)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Nationality (Originale)", x = "Nationality", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none") 

# Creazione del barplot con le categorie accorpate
p2 <- ggplot(grouped_data, aes(x = Nationality, y = Perc, fill = Nationality)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Nationality (Accorpato)", x = "Nationality", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") 

# Affiancare i due grafici
grid.arrange(p1, p2, ncol = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Nationality_Comparison.pdf", plot = grid.arrange(p1, p2, ncol = 2), width = 16, height = 6)


```

```{r}
##### PARENTS QUALIFICATION #####

# Librerie
library(ggplot2)
library(dplyr)
library(here)
library(gridExtra)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)


# Ordinare le categorie originali basandosi sul codice numerico
data$Mothers_qualification <- as.numeric(as.character(data$Mothers_qualification)) 
data <- data[order(data$Mothers_qualification), ]

# Convertire in fattore ordinato per il grafico
data$Mothers_qualification <- factor(data$Mothers_qualification, 
                                     levels = sort(unique(data$Mothers_qualification)))

# Creazione della variabile accorpata con la nuova suddivisione
data$Mothers_qualification_grouped <- recode(data$Mothers_qualification,
                                            # 1 - Higher Education
                                            "2" = "1-Higher Education",  # Higher Education - Bachelor's Degree
                                            "3" = "1-Higher Education",  # Higher Education - Degree
                                            "4" = "1-Higher Education",  # Higher Education - Master's
                                            "5" = "1-Higher Education",  # Higher Education - Doctorate
                                            "40" = "1-Higher Education", # Higher Education - Degree (1st cycle)
                                            "41" = "1-Higher Education", # Specialized Higher Studies Course
                                            "42" = "1-Higher Education", # Professional Higher Technical Course
                                            "43" = "1-Higher Education", # Higher Education - Master (2nd cycle)
                                            "44" = "1-Higher Education", # Higher Education - Doctorate (3rd cycle)
                                            
                                            # 2 - Secondary Education
                                            "1" = "2-Secondary Education",  # Secondary Education - 12th Year of Schooling or Equivalent
                                            "18" = "2-Secondary Education", # General Commerce Course
                                            "22" = "2-Secondary Education", # Technical-Professional Course
                                            "27" = "2-Secondary Education", # 2nd Cycle of the General High School Course
                                            "39" = "2-Secondary Education", # Technological Specialization Course
                                            "6" = "2-Secondary Education",  # Frequency of Higher Education (non completato, quindi accorpato a Secondary)
                                            
                                            # 3 - Basic Education (3º ciclo)
                                            "19" = "3-Basic Education (3º ciclo)", # Basic Education 3rd Cycle (9th/10th/11th Year) or Equivalent
                                            "10" = "3-Basic Education (3º ciclo)", # 11th Year of Schooling - Not Completed
                                            "12" = "3-Basic Education (3º ciclo)", # Other - 11th Year of Schooling
                                            "14" = "3-Basic Education (3º ciclo)", # 10th Year of Schooling
                                            "9"  = "3-Basic Education (3º ciclo)", # 12th Year of Schooling - Not Completed
                                        
                                            # 4 - Basic Education (2º ciclo)
                                            "38" = "4-Basic Education (2º ciclo)", # Basic Education 2nd Cycle (6th/7th/8th Year) or Equivalent
                                            "11" = "4-Basic Education (2º ciclo)", # 7th Year (Old)
                                            "26" = "4-Basic Education (2º ciclo)", # 7th Year of Schooling
                                            "29" = "4-Basic Education (2º ciclo)", # 9th Year of Schooling - Not Completed
                                            "30" = "4-Basic Education (2º ciclo)", # 8th Year of Schooling
                                            
                                            # 5 - Basic Education (1º ciclo)
                                            "37" = "5-Basic Education (1º ciclo)", # Basic Education 1st Cycle (4th/5th Year) or Equivalent
                                            
                                            # 6 - No Qualification
                                            "35" = "6-No Qualification", # Can't Read or Write
                                            "36" = "6-No Qualification", # Can Read Without Having a 4th Year of Schooling
                                            "34" = "6-No Qualification", # Unknown
                                            .default = "6-No Qualification") # Qualsiasi valore non specificato sarà considerato senza qualifica

# Convertire in fattore con ordine predefinito
data$Mothers_qualification_grouped <- factor(data$Mothers_qualification_grouped, 
                                            levels = c("1-Higher Education", 
                                                       "2-Secondary Education", 
                                                       "3-Basic Education (3º ciclo)", 
                                                       "4-Basic Education (2º ciclo)", 
                                                       "5-Basic Education (1º ciclo)", 
                                                       "6-No Qualification"))

# Ordinare le categorie originali basandosi sul codice numerico
data$Fathers_qualification <- as.numeric(as.character(data$Fathers_qualification)) 
data <- data[order(data$Fathers_qualification), ] 

# Convertire in fattore ordinato per il grafico
data$Fathers_qualification <- factor(data$Fathers_qualification, 
                                     levels = sort(unique(data$Fathers_qualification)))

# Creazione della variabile accorpata con la nuova suddivisione
data$Fathers_qualification_grouped <- recode(data$Fathers_qualification,
                                            # 1 - Higher Education
                                            "2" = "1-Higher Education",  # Higher Education - Bachelor's Degree
                                            "3" = "1-Higher Education",  # Higher Education - Degree
                                            "4" = "1-Higher Education",  # Higher Education - Master's
                                            "5" = "1-Higher Education",  # Higher Education - Doctorate
                                            "40" = "1-Higher Education", # Higher Education - Degree (1st cycle)
                                            "41" = "1-Higher Education", # Specialized Higher Studies Course
                                            "42" = "1-Higher Education", # Professional Higher Technical Course
                                            "43" = "1-Higher Education", # Higher Education - Master (2nd cycle)
                                            "44" = "1-Higher Education", # Higher Education - Doctorate (3rd cycle)
                                            
                                            # 2 - Secondary Education
                                            "1" = "2-Secondary Education",  # Secondary Education - 12th Year of Schooling or Equivalent
                                            "18" = "2-Secondary Education", # General Commerce Course
                                            "22" = "2-Secondary Education", # Technical-Professional Course
                                            "27" = "2-Secondary Education", # 2nd Cycle of the General High School Course
                                            "39" = "2-Secondary Education", # Technological Specialization Course
                                            "13" = "2-Secondary Education", # 2nd year complementary high school course
                                            "20" = "2-Secondary Education", # complementary high school course
                                            "25" = "2-Secondary Education", # complementary high school course
                                            "31" = "2-Secondary Education", # General Course of Administration and Commerce
                                            "33" ="2-Secondary Education", # Supplementary Accounting and Administration
                                            "6" = "2-Secondary Education",  # Frequency of Higher Education
                                            
                                            # 3 - Basic Education (3º ciclo)
                                            "19" = "3-Basic Education (3º ciclo)", # Basic Education 3rd Cycle (9th/10th/11th Year) or Equivalent
                                            "10" = "3-Basic Education (3º ciclo)", # 11th Year of Schooling - Not Completed
                                            "12" = "3-Basic Education (3º ciclo)", # Other - 11th Year of Schooling
                                            "14" = "3-Basic Education (3º ciclo)", # 10th Year of Schooling
                                            "9"  = "3-Basic Education (3º ciclo)", # 12th Year of Schooling - Not Completed
                                        
                                            # 4 - Basic Education (2º ciclo)
                                            "38" = "4-Basic Education (2º ciclo)", # Basic Education 2nd Cycle (6th/7th/8th Year) or Equivalent
                                            "11" = "4-Basic Education (2º ciclo)", # 7th Year (Old)
                                            "26" = "4-Basic Education (2º ciclo)", # 7th Year of Schooling
                                            "29" = "4-Basic Education (2º ciclo)", # 9th Year of Schooling - Not Completed
                                            "30" = "4-Basic Education (2º ciclo)", # 8th Year of Schooling
                                            
                                            # 5 - Basic Education (1º ciclo)
                                            "37" = "5-Basic Education (1º ciclo)", # Basic Education 1st Cycle (4th/5th Year) or Equivalent
                                            
                                            # 6 - No Qualification
                                            "35" = "6-No Qualification", # Can't Read or Write
                                            "36" = "6-No Qualification", # Can Read Without Having a 4th Year of Schooling
                                            "34" = "6-No Qualification", # Unknown
                                            .default = "6-No Qualification") # Qualsiasi valore non specificato sarà considerato senza qualifica

# Convertire in fattore con ordine predefinito
data$Fathers_qualification_grouped <- factor(data$Fathers_qualification_grouped, 
                                            levels = c("1-Higher Education", 
                                                       "2-Secondary Education", 
                                                       "3-Basic Education (3º ciclo)", 
                                                       "4-Basic Education (2º ciclo)", 
                                                       "5-Basic Education (1º ciclo)", 
                                                       "6-No Qualification"))



# Calcolo delle frequenze relative per il dataset originale - MADRE
freq_original_mother <- table(data$Mothers_qualification)
original_data_mother <- data.frame(Qualification = names(freq_original_mother), 
                                   Count = as.numeric(freq_original_mother))
original_data_mother$Perc <- original_data_mother$Count / sum(original_data_mother$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate - MADRE
freq_grouped_mother <- table(data$Mothers_qualification_grouped)
grouped_data_mother <- data.frame(Qualification = names(freq_grouped_mother), 
                                  Count = as.numeric(freq_grouped_mother))
grouped_data_mother$Perc <- grouped_data_mother$Count / sum(grouped_data_mother$Count) * 100

# Calcolo delle frequenze relative per il dataset originale - PADRE
freq_original_father <- table(data$Fathers_qualification)
original_data_father <- data.frame(Qualification = names(freq_original_father), 
                                   Count = as.numeric(freq_original_father))
original_data_father$Perc <- original_data_father$Count / sum(original_data_father$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate - PADRE
freq_grouped_father <- table(data$Fathers_qualification_grouped)
grouped_data_father <- data.frame(Qualification = names(freq_grouped_father), 
                                  Count = as.numeric(freq_grouped_father))
grouped_data_father$Perc <- grouped_data_father$Count / sum(grouped_data_father$Count) * 100

# Determinare il massimo valore di Percentuale per sincronizzare gli assi y di tutti i grafici
y_max <- max(original_data_mother$Perc, grouped_data_mother$Perc, 
             original_data_father$Perc, grouped_data_father$Perc)

# Creazione del barplot originale - MADRE
p1 <- ggplot(original_data_mother, aes(x = factor(Qualification, levels = sort(as.numeric(Qualification))), y = Perc, fill = Qualification)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Mother's Qualification (Originale)", x = "Qualification", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") +
  ylim(0, y_max)  

# Creazione del barplot con le categorie accorpate - MADRE
p2 <- ggplot(grouped_data_mother, aes(x = Qualification, y = Perc, fill = Qualification)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Mother's Qualification (Accorpato)", x = "Qualification", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") +
  ylim(0, y_max)  

# Creazione del barplot originale - PADRE
p3 <- ggplot(original_data_father, aes(x = factor(Qualification, levels = sort(as.numeric(Qualification))), y = Perc, fill = Qualification)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Father's Qualification (Originale)", x = "Qualification", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") +
  ylim(0, y_max) 

# Creazione del barplot con le categorie accorpate - PADRE
p4 <- ggplot(grouped_data_father, aes(x = Qualification, y = Perc, fill = Qualification)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Father's Qualification (Accorpato)", x = "Qualification", y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") +
  ylim(0, y_max) 

# Affiancare i quattro grafici in due righe e due colonne
final_plot <- grid.arrange(p1, p2, p3, p4, ncol = 2, nrow = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Parents_Qualification_Comparison.pdf", plot = final_plot, width = 24, height = 12)

print(freq_grouped_mother)
print(freq_grouped_father)
```


```{r}
##### APPLICATION_ORDER - CORREZIONE ANOMALIE #####

# Librerie
library(ggplot2)
library(dplyr)
library(here)
library(gridExtra)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Creazione della variabile corretta accorpando 0 → 1 e 9 → 6
data$Application_order_corrected <- recode(data$Application_order,
                                           "0" = "1", # Sposta 0 in 1
                                           "9" = "6", # Sposta 9 in 6
                                           .default = as.character(data$Application_order)) # Mantiene gli altri valori inalterati

# Creazione delle etichette (1st, 2nd, 3rd, etc.)
ordinal_labels <- function(x) {
  suffix <- c("th", "st", "nd", "rd", rep("th", 6))
  paste0(x, suffix[(x %% 10) + 1])
}

# Convertire la variabile in numerico per ordinamento
data$Application_order <- as.numeric(as.character(data$Application_order))
data$Application_order_corrected <- as.numeric(as.character(data$Application_order_corrected))

# Creare fattori ordinati con etichette ordinali
data$Application_order <- factor(data$Application_order, 
                                 levels = sort(unique(data$Application_order)), 
                                 labels = ordinal_labels(sort(unique(data$Application_order))))

data$Application_order_corrected <- factor(data$Application_order_corrected, 
                                           levels = sort(unique(data$Application_order_corrected)), 
                                           labels = ordinal_labels(sort(unique(data$Application_order_corrected))))

# Calcolo delle frequenze relative per il dataset originale
freq_original <- table(data$Application_order)
original_data <- data.frame(Application_order = names(freq_original), 
                            Count = as.numeric(freq_original))
original_data$Perc <- original_data$Count / sum(original_data$Count) * 100

# Calcolo delle frequenze relative per il dataset corretto
freq_corrected <- table(data$Application_order_corrected)
corrected_data <- data.frame(Application_order = names(freq_corrected), 
                             Count = as.numeric(freq_corrected))
corrected_data$Perc <- corrected_data$Count / sum(corrected_data$Count) * 100

# Creazione del barplot originale con etichette ordinali
p1 <- ggplot(original_data, aes(x = Application_order, y = Perc, fill = Application_order)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Application Order (Originale)", 
       x = "Application Order", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none")

# Creazione del barplot corretto con etichette ordinali
p2 <- ggplot(corrected_data, aes(x = Application_order, y = Perc, fill = Application_order)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Application Order (Corretto)", 
       x = "Application Order", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none")

grid.arrange(p1, p2, ncol = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Application_Order_Comparison.pdf", 
       plot = grid.arrange(p1, p2, ncol = 2), width = 18, height = 6)

print(table(data$Application_order_corrected))

```


```{r}
###### PREVIOUS_QUALIFICATION - ACCORPAMENTO #####

# Librerie
library(ggplot2)
library(dplyr)
library(here)
library(gridExtra)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Creazione della variabile accorpata con la nuova suddivisione
data$Previous_qualification_grouped <- recode(data$Previous_qualification,
                                            # 1 - Higher Education
                                            "2" = "1-Higher Education",  # Higher Education - Bachelor's Degree
                                            "3" = "1-Higher Education",  # Higher Education - Degree
                                            "4" = "1-Higher Education",  # Higher Education - Master's
                                            "5" = "1-Higher Education",  # Higher Education - Doctorate
                                            "40" = "1-Higher Education", # Higher Education - Degree (1st cycle)
                                            "42" = "1-Higher Education", # Professional Higher Technical Course
                                            "43" = "1-Higher Education", # Higher Education - Master (2nd cycle)
                                            
                                            # 2 - Secondary Education
                                            "1" = "2-Secondary Education",  # Secondary Education - 12th Year of Schooling or Equivalent
                                            "6" = "2-Secondary Education",  # Frequency of Higher Education (non completato, quindi accorpato a Secondary)
                                            
                                            # 4 - Technological
                                            "39" = "3-Technological Specialization", # Technological Specialization Course
                                            
                                            
                                            # 3 - Basic Education
                                            "19" = "4-Basic Education", # Basic Education 3rd Cycle (9th/10th/11th Year) or Equivalent
                                            "38" = "4-Basic Education", # Basic Education 2nd Cycle (6th/7th/8th Year) or Equivalent
                                            "9" = "4-Basic Education",  # 12th Year of Schooling - Not Completed
                                            "10" = "4-Basic Education", # 11th Year of Schooling - Not Completed
                                            "12" = "4-Basic Education", # Other - 11th Year of Schooling
                                            "14" = "4-Basic Education", # 10th Year of Schooling
                                            "15" = "4-Basic Education") # 10th Year of Schooling - Not Completed
                                            
                                            

# Convertire in fattore con ordine predefinito
data$Previous_qualification_grouped <- factor(data$Previous_qualification_grouped, 
                                            levels = c("1-Higher Education", 
                                                       "2-Secondary Education",
                                                       "3-Technological Specialization",
                                                       "4-Basic Education"))

# Calcolo delle frequenze relative per il dataset originale
freq_original <- table(data$Previous_qualification)
original_data <- data.frame(Qualification = names(freq_original), 
                            Count = as.numeric(freq_original))
original_data$Perc <- original_data$Count / sum(original_data$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate
freq_grouped <- table(data$Previous_qualification_grouped)
grouped_data <- data.frame(Qualification = names(freq_grouped), 
                           Count = as.numeric(freq_grouped))
grouped_data$Perc <- grouped_data$Count / sum(grouped_data$Count) * 100

# Creazione del barplot originale
p1 <- ggplot(original_data, aes(x = factor(Qualification, levels = sort(as.numeric(Qualification))), 
                                y = Perc, fill = Qualification)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Previous Qualification (Originale)", 
       x = "Previous Qualification", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none")

# Creazione del barplot con le categorie accorpate
p2 <- ggplot(grouped_data, aes(x = Qualification, y = Perc, fill = Qualification)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Previous Qualification (Accorpato)", 
       x = "Previous Qualification", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none")

# Affiancare i due grafici
grid.arrange(p1, p2, ncol = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Previous_Qualification_Comparison.pdf", 
       plot = grid.arrange(p1, p2, ncol = 2), width = 20, height = 6)

print(freq_grouped)

```

```{r}
###### COURSE ######

# Librerie
library(ggplot2)
library(dplyr)
library(here)
library(gridExtra)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Creazione della variabile accorpata 
data$Course_grouped <- recode(data$Course,
    "9500" = "1-Health\nSciences", 
    "9556" = "1-Health\nSciences",
    "9085" = "2-Veterinary\nSciences", 
    "9130" = "2-Veterinary\nSciences",
    "8014" = "3-Social\nSciences",
    "9238" = "3-Social\nSciences",
    "9773" = "3-Social\nSciences",
    "9853" = "3-Social\nSciences",
    "9147" = "4-Business\n& Management",
    "9670" = "4-Business\n& Management",
    "9991" = "4-Business\n& Management",
    "171" = "5-Communication\n& Design",
    "9070" = "5-Communication\n& Design",
    "9119" = "6-Engineering\n& Technology",
    "33" = "6-Engineering\n& Technology",
    "9003" = "7-Agriculture\n& Environment",
    "9254" = "8-Tourism\n& Services")

# Convertire in fattore con ordine predefinito
data$Course_grouped <- factor(data$Course_grouped, 
                                        levels = c("1-Health\nSciences", 
                                                   "2-Veterinary\nSciences",
                                                   "3-Social\nSciences", 
                                                   "4-Business\n& Management",
                                                   "5-Communication\n& Design",
                                                   "6-Engineering\n& Technology",
                                                   "7-Agriculture\n& Environment",
                                                   "8-Tourism\n& Services"))


# Calcolo delle frequenze relative per il dataset originale
freq_original <- table(data$Course)
original_data <- data.frame(Course = names(freq_original), 
                            Count = as.numeric(freq_original))
original_data$Perc <- original_data$Count / sum(original_data$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate
freq_grouped <- table(data$Course_grouped)
grouped_data <- data.frame(Course = names(freq_grouped), 
                           Count = as.numeric(freq_grouped))
grouped_data$Perc <- grouped_data$Count / sum(grouped_data$Count) * 100

# Trovare il massimo valore dell'asse y per la sincronizzazione
max_y <- max(c(original_data$Perc, grouped_data$Perc))

# Creazione del barplot originale
p1 <- ggplot(original_data, aes(x = factor(Course, levels = sort(as.numeric(Course))), 
                                y = Perc, fill = Course)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Course (Originale)", 
       x = "Course", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, max_y)

# Creazione del barplot con le categorie accorpate
p2 <- ggplot(grouped_data, aes(x = Course, y = Perc, fill = Course)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Course (Accorpato)", 
       x = "Course", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none",
        axis.text.x = element_text(size = 10)) +
  ylim(0, max_y)  

# Affiancare i due grafici
combined_plot <- grid.arrange(p1, p2, ncol = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Course_Comparison.pdf", 
       plot = combined_plot, width = 24, height = 6)

print(freq_grouped)



```


```{r}
##### APPLICATION MODE ######

# Librerie
library(ggplot2)
library(dplyr)
library(here)
library(gridExtra)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Creazione della variabile accorpata con la nuova suddivisione
data$Application_mode_grouped <- recode(data$Application_mode,
                                            # 1 - General Contingent
                                            "1" = "1-General Contingent",  # 1st phase - general contingent
                                            "17" = "1-General Contingent", # 2nd phase - general contingent
                                            "18" = "1-General Contingent", # 3rd phase - general contingent
                                            
                                            # 2 - Transfers & Changes
                                            "42" = "2-Transfers & Changes", # Transfer
                                            "43" = "2-Transfers & Changes", # Change of course
                                            "51" = "2-Transfers & Changes", # Change of institution/course
                                            "57" = "2-Transfers & Changes", # Change of institution/course (International)
                                            
                                            # 3 - Older Students
                                            "39" = "3-Older Students", # Over 23 years old
                                            
                                            # 4 - Special Diplomas
                                            "7" = "4-Special Diplomas", # Holders of other higher courses
                                            "44" = "4-Special Diplomas", # Technological specialization diploma holders
                                            "53" = "4-Special Diplomas", # Short cycle diploma holders
                                            
                                            # 5 - Special Contingent & Ordinances
                                            "2" = "5-Special Contingent & Ordinances", # Ordinance No. 612/93
                                            "5" = "5-Special Contingent & Ordinances", # 1st phase - special contingent (Azores Island)
                                            "10" = "5-Special Contingent & Ordinances", # Ordinance No. 854-B/99
                                            "15" = "5-Special Contingent & Ordinances", # International student (bachelor)
                                            "16" = "5-Special Contingent & Ordinances", # 1st phase - special contingent (Madeira Island)
                                            "26" = "5-Special Contingent & Ordinances", # Ordinance No. 533-A/99, item b2) (Different Plan)
                                            "27" = "5-Special Contingent & Ordinances") # Ordinance No. 533-A/99, item b3 (Other Institution)

# Convertire in fattore con ordine predefinito
data$Application_mode_grouped <- factor(data$Application_mode_grouped, 
                                        levels = c("1-General Contingent", 
                                                   "2-Transfers & Changes", 
                                                   "3-Older Students",
                                                   "4-Special Diplomas",
                                                   "5-Special Contingent & Ordinances"))

# Calcolo delle frequenze relative per il dataset originale
freq_original <- table(data$Application_mode)
original_data <- data.frame(Application_mode = names(freq_original), 
                            Count = as.numeric(freq_original))
original_data$Perc <- original_data$Count / sum(original_data$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate
freq_grouped <- table(data$Application_mode_grouped)
grouped_data <- data.frame(Application_mode = names(freq_grouped), 
                           Count = as.numeric(freq_grouped))
grouped_data$Perc <- grouped_data$Count / sum(grouped_data$Count) * 100

# Determinazione del limite massimo per l'asse Y
y_max <- max(original_data$Perc, grouped_data$Perc)

# Creazione del barplot originale
p1 <- ggplot(original_data, aes(x = factor(Application_mode, levels = sort(as.numeric(Application_mode))), 
                                y = Perc, fill = Application_mode)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Application Mode (Originale)", 
       x = "Application Mode", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") +
  ylim(0, y_max)

# Creazione del barplot con le categorie accorpate
p2 <- ggplot(grouped_data, aes(x = Application_mode, y = Perc, fill = Application_mode)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Application Mode (Accorpato)", 
       x = "Application Mode", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none") +
  ylim(0, y_max)  

# Affiancare i due grafici
combined_plot <- grid.arrange(p1, p2, ncol = 2)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Application_Mode_Comparison.pdf", 
       plot = combined_plot, width = 20, height = 6)

print(freq_grouped)


```

```{r}
######## PARENTS OCCUPATION #######

# Librerie
library(ggplot2)
library(dplyr)
library(here)
library(gridExtra)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# Creazione della variabile accorpata 
data$Fathers_occupation_grouped <- recode(data$Fathers_occupation,
    # 1 - High-Level Professionals 
    "1" = "1-High-Level\nProfessionals",  
    "2" = "1-High-Level\nProfessionals",  
    "3" = "1-High-Level\nProfessionals",  
    "112" = "1-High-Level\nProfessionals",  
    "114" = "1-High-Level\nProfessionals",  
    "121" = "1-High-Level\nProfessionals", 
    "122" = "1-High-Level\nProfessionals",  
    "123" = "1-High-Level\nProfessionals",  
    "124" = "1-High-Level\nProfessionals",
    "132" = "1-High-Level\nProfessionals",
    
    # 2 - Administrative & Sales Workers
    "4" = "2-Admin &\nSales Workers",  
    "141" = "2-Admin &\nSales Workers",  
    "143" = "2-Admin &\nSales Workers",  
    "144" = "2-Admin &\nSales Workers",  
    "151" = "2-Admin &\nSales Workers",  
    "152" = "2-Admin &\nSales Workers",  
    
    # 3 - Service & Security Workers 
    "5" = "3-Service &\nSecurity Workers",  
    "153" = "3-Service &\nSecurity Workers",  
    "154" = "3-Service &\nSecurity Workers",  
    "134" = "3-Service &\nSecurity Workers",  
    
    # 4 - Agriculture & Skilled Workers
    "6" = "4-Agriculture &\nSkilled Workers",  
    "161" = "4-Agriculture &\nSkilled Workers",  
    "163" = "4-Agriculture &\nSkilled Workers",  
    
    # 5 - Industry & Construction
    "7" = "5-Industry &\nConstruction",  
    "171" = "5-Industry &\nConstruction",  
    "172" = "5-Industry &\nConstruction",  
    "174" = "5-Industry &\nConstruction",  
    "175" = "5-Industry &\nConstruction",  
    
    # 6 - Machine & Transport Operators 
    "8" = "6-Machine &\nTransport Operators",  
    "181" = "6-Machine &\nTransport Operators",  
    "182" = "6-Machine &\nTransport Operators",  
    "183" = "6-Machine &\nTransport Operators",  
    "131" = "6-Machine &\nTransport Operators", 
    "135" = "6-Machine &\nTransport Operators", 
    
    # 7 - Unskilled Workers
    "9" = "7-Unskilled\nWorkers",  
    "192" = "7-Unskilled\nWorkers",  
    "193" = "7-Unskilled\nWorkers",  
    "194" = "7-Unskilled\nWorkers",  
    "195" = "7-Unskilled\nWorkers",  
    
    # 8 - Armed Forces
    "10" = "8-Armed\nForces",  
    "101" = "8-Armed\nForces",  
    "102" = "8-Armed\nForces",  
    "103" = "8-Armed\nForces",  
    
    # 9 - Student
    "0" = "9-Student",  
    
    # 10 - Other/Unknown
    "90" = "10-Other/\nUnknown",  
    "99" = "10-Other/\nUnknown")

# Convertire in fattore con ordine predefinito
data$Fathers_occupation_grouped <- factor(data$Fathers_occupation_grouped, 
                                          levels = c("1-High-Level\nProfessionals", 
                                                     "2-Admin &\nSales Workers", 
                                                     "3-Service &\nSecurity Workers",
                                                     "4-Agriculture &\nSkilled Workers",
                                                     "5-Industry &\nConstruction",
                                                     "6-Machine &\nTransport Operators",
                                                     "7-Unskilled\nWorkers",
                                                     "8-Armed\nForces",
                                                     "9-Student",
                                                     "10-Other/\nUnknown"))

# Creazione della variabile accorpata per Mothers_occupation
data$Mothers_occupation_grouped <- recode(data$Mothers_occupation,
    # 1 - High-Level Professionals
    "1" = "1-High-Level\nProfessionals",  
    "2" = "1-High-Level\nProfessionals",  
    "122" = "1-High-Level\nProfessionals",  
    "123" = "1-High-Level\nProfessionals",  
    "125" = "1-High-Level\nProfessionals",  
    
    # 2 - Administrative & Sales Workers
    "4" = "2-Admin &\nSales Workers",  
    "141" = "2-Admin &\nSales Workers",  
    "143" = "2-Admin &\nSales Workers",  
    "144" = "2-Admin &\nSales Workers",  
    "151" = "2-Admin &\nSales Workers",  
    "152" = "2-Admin &\nSales Workers",  
    
    # 3 - Service & Security Workers
    "5" = "3-Service &\nSecurity Workers",
    "134" = "3-Service &\nSecurity Workers",
    "153" = "3-Service &\nSecurity Workers",  
    "191" = "3-Service &\nSecurity Workers",  
    
    # 4 - Agriculture & Skilled Workers
    "6" = "4-Agriculture &\nSkilled Workers",  
    "171" = "4-Agriculture &\nSkilled Workers",  
    
    # 5 - Industry & Construction
    "7" = "5-Industry &\nConstruction",  
    "173" = "5-Industry &\nConstruction",  
    "175" = "5-Industry &\nConstruction",  
    
    # 6 - Machine & Transport Operators
    "3" = "6-Machine &\nTransport Operators", 
    "8" = "6-Machine &\nTransport Operators",  
    "131" = "6-Machine &\nTransport Operators",  
    "132" = "6-Machine &\nTransport Operators",  
    
    # 7 - Unskilled Workers
    "9" = "7-Unskilled\nWorkers",  
    "192" = "7-Unskilled\nWorkers",  
    "193" = "7-Unskilled\nWorkers",  
    "194" = "7-Unskilled\nWorkers",  
    
    # 8 - Armed Forces
    "10" = "8-Armed\nForces",  
    
    # 9 - Student
    "0" = "9-Student",  
    
    # 10 - Other/Unknown
    "90" = "10-Other/\nUnknown",  
    "99" = "10-Other/\nUnknown")

# Convertire in fattore con ordine predefinito
data$Mothers_occupation_grouped <- factor(data$Mothers_occupation_grouped, 
                                          levels = c("1-High-Level\nProfessionals", 
                                                     "2-Admin &\nSales Workers", 
                                                     "3-Service &\nSecurity Workers",
                                                     "4-Agriculture &\nSkilled Workers",
                                                     "5-Industry &\nConstruction",
                                                     "6-Machine &\nTransport Operators",
                                                     "7-Unskilled\nWorkers",
                                                     "8-Armed\nForces",
                                                     "9-Student",
                                                     "10-Other/\nUnknown"))

# Calcolo delle frequenze relative per il dataset originale (Padre)
freq_original_fathers <- table(data$Fathers_occupation)
original_data_fathers <- data.frame(Occupation = names(freq_original_fathers), 
                                    Count = as.numeric(freq_original_fathers))
original_data_fathers$Perc <- original_data_fathers$Count / sum(original_data_fathers$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate (Padre)
freq_grouped_fathers <- table(data$Fathers_occupation_grouped)
grouped_data_fathers <- data.frame(Occupation = names(freq_grouped_fathers), 
                                   Count = as.numeric(freq_grouped_fathers))
grouped_data_fathers$Perc <- grouped_data_fathers$Count / sum(grouped_data_fathers$Count) * 100

# Calcolo delle frequenze relative per il dataset originale (Madre)
freq_original_mothers <- table(data$Mothers_occupation)
original_data_mothers <- data.frame(Occupation = names(freq_original_mothers), 
                                    Count = as.numeric(freq_original_mothers))
original_data_mothers$Perc <- original_data_mothers$Count / sum(original_data_mothers$Count) * 100

# Calcolo delle frequenze relative per il dataset con le categorie accorpate (Madre)
freq_grouped_mothers <- table(data$Mothers_occupation_grouped)
grouped_data_mothers <- data.frame(Occupation = names(freq_grouped_mothers), 
                                   Count = as.numeric(freq_grouped_mothers))
grouped_data_mothers$Perc <- grouped_data_mothers$Count / sum(grouped_data_mothers$Count) * 100

# Trova il massimo valore di frequenza relativa per sincronizzare l'asse y tra tutti i grafici
max_y <- max(c(original_data_fathers$Perc, grouped_data_fathers$Perc, 
               original_data_mothers$Perc, grouped_data_mothers$Perc))

# Creazione del barplot con le categorie accorpate con asse y sincronizzato (Padre)
p2 <- ggplot(grouped_data_fathers, aes(x = reorder(Occupation, as.numeric(factor(Occupation, levels = levels(data$Fathers_occupation_grouped)))), 
                                       y = Perc, fill = Occupation)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Father's Occupation (Accorpato)", 
       x = "Occupation", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  ylim(0, max_y) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none")

# Creazione del barplot con le categorie accorpate con asse y sincronizzato (Madre)
p4 <- ggplot(grouped_data_mothers, aes(x = reorder(Occupation, as.numeric(factor(Occupation, levels = levels(data$Mothers_occupation_grouped)))), 
                                       y = Perc, fill = Occupation)) +
  geom_bar(stat = "identity", width = 0.7) +
  labs(title = "Barplot: Mother's Occupation (Accorpato)", 
       x = "Occupation", 
       y = "Frequenza Relativa (%)") +
  theme_minimal() +
  geom_text(aes(label = paste0(round(Perc, 1), "%")), vjust = -0.5, size = 4) +
  ylim(0, max_y) +
  theme(plot.title = element_text(hjust = 0.5, face="bold"),
        legend.position = "none")

# Disporre i grafici in verticale (uno sopra l'altro)
combined_plot <- grid.arrange(p1, p2, p3, p4, ncol = 1)

# Salvataggio del grafico in PDF
ggsave("Grafici/Barplot_Occupation_Comparison.pdf", 
       plot = combined_plot, width = 16, height = 20)

print(freq_grouped_fathers)
print(freq_grouped_mothers)



```


```{r}
# Librerie necessarie
library(dplyr)
library(here)

# Caricamento Dataset
data <- read.csv(here("dataset/dataMod.csv"), sep = ",", header = TRUE, check.names = FALSE)

# ---- Aggregazione delle variabili categoriche ----

## 1. Marital Status
data <- data %>%
  mutate(Marital_status = recode(Marital_status,
                                 "1" = "1",
                                 "2" = "2",
                                 "5" = "2",
                                 "3" = "3",
                                 "4" = "3",
                                 "6" = "3"))

## 2. Nationality
data <- data %>%
  mutate(Nationality = recode(Nationality,
                              "1" = "1",
                              .default = "2"))

## 3. Mother's Qualification
data <- data %>%
  mutate(Mothers_qualification = recode(Mothers_qualification,
                                        "2" = "1", "3" = "1", "4" = "1", "5" = "1", 
                                        "40" = "1", "41" = "1", "42" = "1", "43" = "1", "44" = "1",
                                        "1" = "2", "6" = "2", "18" = "2", "22" = "2", "27" = "2", "39" = "2",
                                        "19" = "3", "10" = "3", "12" = "3", "14" = "3", "9"  = "3",
                                        "38" = "4", "11" = "4", "26" = "4", "29" = "4", "30" = "4",
                                        "37" = "5",
                                        .default = "6"))

## 4. Father's Qualification (stessa logica della madre)
data <- data %>%
  mutate(Fathers_qualification = Mothers_qualification)

## 5. Mother's Occupation
data <- data %>%
  mutate(Mothers_occupation = recode(Mothers_occupation,
                                     "1" = "1", "2" = "1", "122" = "1", "123" = "1", "125" = "1",
                                     "4" = "2", "141" = "2", "143" = "2", "144" = "2", "151" = "2", "152" = "2",
                                     "5" = "3", "153" = "3", "191" = "3",
                                     "6" = "4", "171" = "4",
                                     "7" = "5", "173" = "5", "175" = "5",
                                     "8" = "6", "131" = "6", "132" = "6",
                                     "9" = "7", "192" = "7", "193" = "7", "194" = "7",
                                     "10" = "8",
                                     "0" = "9",
                                     .default = "10"))

## 6. Father's Occupation (stessa logica della madre)
data <- data %>%
  mutate(Fathers_occupation = recode(Fathers_occupation,
                                     "1" = "1", "2" = "1", "3" = "1", "112" = "1", "114" = "1", "121" = "1",
                                     "122" = "1", "123" = "1", "124" = "1", "132" = "1",
                                     "4" = "2", "141" = "2", "143" = "2", "144" = "2", "151" = "2", "152" = "2",
                                     "5" = "3", "153" = "3", "154" = "3", "134" = "3",
                                     "6" = "4", "161" = "4", "163" = "4",
                                     "7" = "5", "171" = "5", "172" = "5", "174" = "5", "175" = "5",
                                     "8" = "6", "181" = "6", "182" = "6", "183" = "6", "131" = "6", "135" = "6",
                                     "9" = "7", "192" = "7", "193" = "7", "194" = "7", "195" = "7",
                                     "10" = "8", "101" = "8", "102" = "8", "103" = "8",
                                     "0" = "9",
                                     .default = "10"))

## 7. Application Mode
data <- data %>%
  mutate(Application_mode = recode(Application_mode,
                                   "1" = "1", "17" = "1", "18" = "1",
                                   "42" = "2", "43" = "2", "51" = "2", "57" = "2",
                                   "39" = "3",
                                   "7" = "4", "44" = "4", "53" = "4",
                                   .default = "5"))

## 8. Previous Qualification
data <- data %>%
  mutate(Previous_qualification = recode(Previous_qualification,
                                         "2" = "1", "3" = "1", "4" = "1", "5" = "1",
                                         "40" = "1", "42" = "1", "43" = "1",
                                         "1" = "2", "6" = "2",
                                         "39" = "3",
                                         .default = "4"))

## 9. Course
data <- data %>%
  mutate(Course = recode(Course,
                         "9500" = "1", "9556" = "1",
                         "9085" = "2", "9130" = "2",
                         "8014" = "3", "9238" = "3", "9773" = "3", "9853" = "3",
                         "9147" = "4", "9670" = "4", "9991" = "4",
                         "171" = "5", "9070" = "5",
                         "9119" = "6", "33" = "6",
                         "9003" = "7",
                         "9254" = "8"))

## 10. Application Order (correzione anomalie)
data <- data %>%
  mutate(Application_order = case_when(
    Application_order == 0 ~ 1,
    Application_order == 9 ~ 6,
    TRUE ~ as.numeric(Application_order)
  ))

# ---- Salvataggio del dataset aggregato ----
write.csv(data, here("dataset/data_aggregated.csv"), row.names = FALSE)

print("Dataset aggregato salvato correttamente come 'data_aggregated.csv'.")

```
